---
version: "2"

services:
  proxy:
    volumes:
      - /data/nginx_config:/etc/nginx
      - /data/nginx_releasenote:/usr/share/nginx/html

  ldap:
    volumes:
      - /data/ldap_db:/var/lib/ldap
      - /data/ldap_static:/etc/ldap
      - /data/ldap_slapd:/var/lib/slapd
      - /data/ldap_certs:/etc/ssl/certs
      - /data/ldap_osixia:/osixia
      - /data/ldap_export:/backup

  gitlab:
    volumes:
      - /data/gitlab_conf:/etc/gitlab
      - /data/gitlab_logs:/var/log/gitlab
      - /data/gitlab_data:/var/opt/gitlab

  sensu-api:
    volumes:
      - /data/sensu_api_conf:/etc/sensu/conf.d
      - /data/sensu_checks:/etc/sensu/check.d
      - /data/sensu_handlers:/etc/sensu/handlers

  sensu-server:
    volumes:
      - /data/sensu_server_conf:/etc/sensu/conf.d
      - /data/sensu_checks:/etc/sensu/check.d
      - /data/sensu_handlers:/etc/sensu/handlers

  sensu-client:
    volumes:
      - /data/sensu_client_conf:/etc/sensu/conf.d

  sensu-redis:
    volumes:
      - /data/sensu_redis_data:/data

  sonar:
    volumes:
      - /tmp/sonar_data:/opt/sonarqube/data
      - /data/sonar_extensions:/opt/sonarqube/extensions
      - /data/sonar_logs:/opt/sonarqube/logs

  jenkins:
    user: root
    volumes:
      - /data/jenkins_home:/var/jenkins_home
#
# #   jenkins-slave-java:
#     volumes:
#       - ${SLAVE_MOUNT_PATH_JAVA}:/workspace
#
#   jenkins-slave-node:
#     volumes:
#       - ${SLAVE_MOUNT_PATH_NODE}:/workspace
#
#   jenkins-slave-node:
#     volumes:
#       - ${SLAVE_MOUNT_PATH_NODE_4}:/workspace
#
#   jenkins-slave-ansible:
#     volumes:
#       - ${SLAVE_MOUNT_PATH_ANSIBLE}:/workspace
#
  # selenium-node-chrome:
  #   volumes:
  #     - /data/selenium_config:/var/selenium-config
  # selenium-node-firefox:
  #   volumes:
  #     - /data/selenium_config:/var/selenium-config

  nexus:
    volumes:
      - /data/nexus_sonatype_work:/sonatype-work

  sftp:
    volumes:
      - /sftp/users.conf:/etc/sftp-users.conf:ro
      - /sftp/data:/home
      - /sftp/sftp.d:/etc/sftp.d

  openvpn:
    volumes:
      - /data/openvpn:/etc/openvpn
